name: fooddeliveryapp
description: A new Flutter project.

# Prevent the package from being published to pub.dev.
publish_to: 'none' 

# Version of the app
version: 1.0.0+1

# Flutter and Dart SDK version
environment:
  sdk: '>=3.6.0 <4.0.0'

# Project dependencies
dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.7
  random_string: ^2.3.1
  shared_preferences: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Asset configurations
  assets:
    - images/

  # Custom fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
