// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcbiDOyIWI27RmHuMa1b_BEcryxLBH20c',
    appId: '1:413268901733:web:868d251dbb95e7bc2f2b8c',
    messagingSenderId: '413268901733',
    projectId: 'fooddelivery-app-a9de5',
    authDomain: 'fooddelivery-app-a9de5.firebaseapp.com',
    storageBucket: 'fooddelivery-app-a9de5.firebasestorage.app',
    measurementId: 'G-QSQ019FVGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiKu6oq0OKoY_ZaJ2H1eG2C0g22TVtFPc',
    appId: '1:413268901733:android:c851564798272ee52f2b8c',
    messagingSenderId: '413268901733',
    projectId: 'fooddelivery-app-a9de5',
    storageBucket: 'fooddelivery-app-a9de5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ownZkH4egpIQdNrKgz3LBDurXmsG0qU',
    appId: '1:413268901733:ios:128786112b2a23642f2b8c',
    messagingSenderId: '413268901733',
    projectId: 'fooddelivery-app-a9de5',
    storageBucket: 'fooddelivery-app-a9de5.firebasestorage.app',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ownZkH4egpIQdNrKgz3LBDurXmsG0qU',
    appId: '1:413268901733:ios:128786112b2a23642f2b8c',
    messagingSenderId: '413268901733',
    projectId: 'fooddelivery-app-a9de5',
    storageBucket: 'fooddelivery-app-a9de5.firebasestorage.app',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcbiDOyIWI27RmHuMa1b_BEcryxLBH20c',
    appId: '1:413268901733:web:e80bc7b007c5feae2f2b8c',
    messagingSenderId: '413268901733',
    projectId: 'fooddelivery-app-a9de5',
    authDomain: 'fooddelivery-app-a9de5.firebaseapp.com',
    storageBucket: 'fooddelivery-app-a9de5.firebasestorage.app',
    measurementId: 'G-ZYL74XNB0V',
  );
}
